# Generated by Django 5.1.1 on 2024-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
