# Generated by Django 5.1.1 on 2024-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
