# Generated by Django 5.1.1 on 2024-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabma', '0003_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandevents',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/news-events'),
        ),
    ]
