# Generated by Django 5.1.1 on 2024-10-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wabma', '0004_newsandevents_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsandevents',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
